// app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="w-full p-4 bg-gray-100 border-b shadow-sm">
            <nav className="flex gap-6 text-lg font-medium text-black">
                <Link href="/cube" className="hover:underline">Cube</Link>
                <Link href="/face" className="hover:underline">Face</Link>
            </nav>
        </header>
        <main>{children}</main>
        </body>
        </html>
    );
}
